#!/usr/bin/env python3
"""Changelog generator — derive ``<generatedDir>/CHANGELOG.md`` from git history.

Reads the Conventional Commits in ``git log``, groups them by SemVer tag (``v*``)
and, within each version, by commit type. Deterministic for a given history, so
the CI docs-freshness check is stable (Forge Principle 6).

Usage:
  python3 -m forge_tools.changelog              # write <generatedDir>/CHANGELOG.md
  python3 -m forge_tools.changelog --out FILE    # write to FILE
  python3 -m forge_tools.changelog --check        # exit 1 + diff if stale

Runs without a project stack present; with no git history it emits a valid
"no commits" document.
"""

import os
import re
import subprocess
import sys
from typing import List, NamedTuple, Optional, Tuple

from . import common

DEFAULT_OUT_BASENAME = "CHANGELOG.md"

# Section order + label per Conventional Commit type. Stack-neutral, English.
TYPE_SECTIONS = [
    ("feat", "Features"),
    ("fix", "Fixes"),
    ("perf", "Performance"),
    ("refactor", "Refactoring"),
    ("docs", "Documentation"),
    ("test", "Tests"),
    ("build", "Build"),
    ("ci", "CI/CD"),
    ("chore", "Chores"),
    ("style", "Style"),
    ("revert", "Reverts"),
]
KNOWN_TYPES = {t for t, _ in TYPE_SECTIONS}

# Unit separator — unlikely to appear in a commit subject.
FIELD_SEP = "\x1f"

# Prompt-suite bookkeeping commits are tracking, not product change; skipping
# them keeps the changelog from being perpetually "stale" right after a feature
# commit is followed by a state.json bump.
SKIP_SUBJECT = re.compile(r"^chore\(prompts\)")

HEADER = (
    "<!-- GENERATED by tools/forge_tools/changelog.py from Conventional Commits.\n"
    "     Do not edit by hand: run `make forge-changelog` or `make forge-sync-docs`. -->"
)

CONVENTIONAL = re.compile(r"^(\w+)(?:\(([^)]+)\))?(!)?:\s*(.+)$")


class Commit(NamedTuple):
    short_hash: str
    subject: str


class Parsed(NamedTuple):
    type: str
    scope: Optional[str]
    breaking: bool
    description: str


def _git(args: List[str]) -> str:
    try:
        out = subprocess.run(
            ["git"] + args,
            cwd=common.REPO_ROOT,
            stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL,
            encoding="utf-8",
        )
        return out.stdout or ""
    except (OSError, subprocess.SubprocessError):
        return ""


def _version_tags() -> List[str]:
    out = _git(["tag", "--sort=-creatordate", "--list", "v*"])
    return [t.strip() for t in out.splitlines() if t.strip()]


def _commits_in_range(rng: str) -> List[Commit]:
    out = _git(
        ["log", "--no-merges", "--pretty=format:%h{}%s".format(FIELD_SEP), rng]
    )
    if not out.strip():
        return []
    commits: List[Commit] = []
    for line in out.splitlines():
        parts = line.split(FIELD_SEP)
        short = parts[0].strip()
        subject = (parts[1].strip() if len(parts) > 1 else "")
        if not short:
            continue
        if SKIP_SUBJECT.match(subject):
            continue
        commits.append(Commit(short, subject))
    return commits


def parse_conventional(subject: str) -> Parsed:
    m = CONVENTIONAL.match(subject)
    if not m:
        return Parsed("other", None, False, subject)
    typ, scope, bang, desc = m.group(1), m.group(2), m.group(3), m.group(4)
    return Parsed(
        typ if typ in KNOWN_TYPES else "other",
        scope or None,
        bool(bang),
        desc,
    )


def _render_entry(commit: Commit, show_hash: bool) -> str:
    p = parse_conventional(commit.subject)
    scope = "**{}:** ".format(p.scope) if p.scope else ""
    breaking = " ⚠️ BREAKING" if p.breaking else ""
    suffix = " (`{}`)".format(commit.short_hash) if show_hash else ""
    return "- {}{}{}{}".format(scope, p.description, suffix, breaking)


def _render_section(commits: List[Commit], show_hash: bool) -> str:
    by_type = {}
    others: List[Commit] = []
    for c in commits:
        p = parse_conventional(c.subject)
        if p.type == "other":
            others.append(c)
        else:
            by_type.setdefault(p.type, []).append(c)

    lines: List[str] = []
    for typ, label in TYPE_SECTIONS:
        bucket = by_type.get(typ)
        if not bucket:
            continue
        lines.append("#### {}".format(label))
        lines.append("")
        for c in bucket:
            lines.append(_render_entry(c, show_hash))
        lines.append("")
    if others:
        lines.append("#### Other")
        lines.append("")
        for c in others:
            suffix = " (`{}`)".format(c.short_hash) if show_hash else ""
            lines.append("- {}{}".format(c.subject, suffix))
        lines.append("")
    return "\n".join(lines)


def build_report() -> str:
    name = common.project_name()
    tags = _version_tags()

    lines: List[str] = [HEADER, "", "# {} — Changelog".format(name), ""]
    lines.append(
        "Generated from **Conventional Commits**. Versions are marked by SemVer "
        "tags (`v*`); anything not yet released appears under **Unreleased**. "
        "Unreleased entries omit the commit hash (it is not stable until "
        "released — e.g. it changes on an amend/rebase); released sections pin "
        "the hash for permanence."
    )
    lines.append("")

    ranges: List[Tuple[str, str]] = []
    if tags:
        ranges.append(("Unreleased", "{}..HEAD".format(tags[0])))
        for i, tag in enumerate(tags):
            nxt = tags[i + 1] if i + 1 < len(tags) else None
            ranges.append((tag, "{}..{}".format(nxt, tag) if nxt else tag))
    else:
        ranges.append(("Unreleased", "HEAD"))

    any_commits = False
    for title, rng in ranges:
        commits = _commits_in_range(rng)
        if not commits:
            continue
        any_commits = True
        # Unreleased hashes are not yet stable (amend/rebase changes them), so
        # the docs-freshness gate would chase its own tail; released sections,
        # being behind an immutable tag, pin the hash.
        show_hash = title != "Unreleased"
        lines.append("## {}".format(title))
        lines.append("")
        lines.append(_render_section(commits, show_hash))

    if not any_commits:
        lines.append("_No commits in history yet._")
        lines.append("")

    return "\n".join(lines).rstrip("\n") + "\n"


def main(argv: List[str]) -> int:
    default_out = common.repo_path(common.generated_dir(), DEFAULT_OUT_BASENAME)
    check, out_path = common.parse_common_args(argv, default_out)
    content = build_report()
    return common.emit(content, out_path, check, "changelog")


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
