#!/usr/bin/env python3
"""Traceability generator — scan source for ``@requirement`` / ``@rule`` tags.

Emits ``<generatedDir>/traceability.md`` (a matrix: requirement · source doc ·
code files · test files · status), linking requirement -> code -> test
(Forge Principle 7). The scan globs and tag aliases come from
``forge.config.json`` (with stack-neutral defaults), so nothing about a
specific language or layout is baked in.

Tag forms recognized (generalized from PedPlus's ``@requirement RFxx`` /
``@businessRule RNxx``):

  * ``@requirement <ID>``  — links a requirement id (FR/NFR/CR/UC/EN)
  * ``@rule <ID>`` / ``@businessRule <ID>`` — links a business rule (BR)

Both keyword sets are configurable via ``traceability.tagAliases``.

Usage:
  python3 -m forge_tools.traceability             # write <generatedDir>/traceability.md
  python3 -m forge_tools.traceability --out FILE   # write to FILE
  python3 -m forge_tools.traceability --check       # exit 1 + diff if stale

Runs without a real project stack present: with no source files and no
requirement docs it still emits a well-formed (empty) matrix.
"""

import fnmatch
import os
import re
import sys
from typing import Dict, List, Set, Tuple

from . import common
from .requirements import parse_requirements, Requirement

DEFAULT_OUT_BASENAME = "traceability.md"

# Directories never worth scanning, in any ecosystem.
IGNORED_DIRS = {
    ".git",
    "node_modules",
    "vendor",
    ".venv",
    "venv",
    "__pycache__",
    "dist",
    "build",
    "out",
    "target",
    "coverage",
    ".cache",
    ".nx",
    ".idea",
}

# Files we never treat as scannable source (binaries, lockfiles, the matrix
# itself). Everything else matched by the globs is read as text.
SKIP_BASENAMES = {DEFAULT_OUT_BASENAME}
BINARY_EXTS = {
    ".png", ".jpg", ".jpeg", ".gif", ".webp", ".ico", ".svg", ".pdf",
    ".zip", ".gz", ".tar", ".bin", ".lock", ".woff", ".woff2", ".ttf",
}

HEADER = (
    "<!-- GENERATED by tools/forge_tools/traceability.py from @requirement /\n"
    "     @rule tags across the source. Do not edit by hand: run\n"
    "     `make forge-traceability` or `make forge-sync-docs`. -->"
)


def _tag_patterns(aliases: Dict[str, List[str]]) -> Dict[str, "re.Pattern[str]"]:
    """Build one regex per link kind from the configured keyword aliases."""
    patterns: Dict[str, "re.Pattern[str]"] = {}
    for kind, keywords in aliases.items():
        if not keywords:
            continue
        alt = "|".join(re.escape(k) for k in keywords)
        # @<keyword> <ID>  where ID starts with letters then digits/dots/hyphens
        patterns[kind] = re.compile(
            r"@(?:" + alt + r")\s+([A-Za-z]+[-]?\d[\w.\-]*)"
        )
    return patterns


def _is_test_file(rel_path: str) -> bool:
    base = os.path.basename(rel_path)
    # Common cross-ecosystem test markers; also handles generator .template files.
    if re.search(r"\.(spec|test)\.[\w.]*$", base):
        return True
    if re.search(r"_test\.[\w.]*$", base):
        return True
    if re.search(r"(^|/)tests?/", rel_path):
        return True
    if base.startswith("test_"):
        return True
    return False


def _iter_glob_files(globs: List[str]) -> List[str]:
    """Resolve the configured globs into a sorted list of repo-relative files.

    Uses an os.walk with fnmatch so ``**`` works on Python 3.9 without
    ``glob(recursive=...)`` edge cases, and so ignored directories are pruned
    cheaply.
    """
    matched: Set[str] = set()
    for dirpath, dirnames, filenames in os.walk(common.REPO_ROOT):
        # Prune ignored directories in place.
        dirnames[:] = [d for d in dirnames if d not in IGNORED_DIRS]
        for fn in filenames:
            abs_path = os.path.join(dirpath, fn)
            rel = common.rel_to_repo(abs_path)
            if fn in SKIP_BASENAMES:
                continue
            ext = os.path.splitext(fn)[1].lower()
            if ext in BINARY_EXTS:
                continue
            if _matches_any(rel, globs):
                matched.add(rel)
    return sorted(matched)


def _matches_any(rel: str, globs: List[str]) -> bool:
    for pattern in globs:
        if _glob_match(rel, pattern):
            return True
    return False


def _glob_match(rel: str, pattern: str) -> bool:
    """Match a repo-relative path against a glob supporting ``**``.

    fnmatch does not treat ``**`` specially, so we translate the pattern into a
    regex where ``**`` spans path separators and ``*`` does not.
    """
    # Normalize: a pattern like "libs/**/*" should also match "libs/a" files.
    regex = _glob_to_regex(pattern)
    return regex.match(rel) is not None


_GLOB_CACHE: Dict[str, "re.Pattern[str]"] = {}


def _glob_to_regex(pattern: str) -> "re.Pattern[str]":
    cached = _GLOB_CACHE.get(pattern)
    if cached is not None:
        return cached
    i = 0
    out = ["^"]
    n = len(pattern)
    while i < n:
        c = pattern[i]
        if c == "*":
            if i + 1 < n and pattern[i + 1] == "*":
                # '**' -> any chars incl. '/'
                out.append(".*")
                i += 2
                # swallow a following '/' so 'a/**/b' matches 'a/b'
                if i < n and pattern[i] == "/":
                    out.append("(?:/)?")
                    i += 1
                continue
            out.append("[^/]*")
        elif c == "?":
            out.append("[^/]")
        elif c == ".":
            out.append(r"\.")
        else:
            out.append(re.escape(c))
        i += 1
    out.append("$")
    compiled = re.compile("".join(out))
    _GLOB_CACHE[pattern] = compiled
    return compiled


def scan(globs: List[str], aliases: Dict[str, List[str]]) -> Dict[str, Dict[str, Set[str]]]:
    """Scan the source for tags.

    Returns ``{ id: {"code": set(files), "tests": set(files)} }`` covering every
    id referenced by any tag, whether or not it is declared.
    """
    patterns = _tag_patterns(aliases)
    index: Dict[str, Dict[str, Set[str]]] = {}
    for rel in _iter_glob_files(globs):
        abs_path = common.repo_path(rel)
        try:
            with open(abs_path, encoding="utf-8") as fh:
                content = fh.read()
        except (UnicodeDecodeError, OSError):
            continue
        is_test = _is_test_file(rel)
        for _kind, pattern in patterns.items():
            for match in pattern.finditer(content):
                rid = match.group(1)
                bucket = index.setdefault(rid, {"code": set(), "tests": set()})
                if is_test:
                    bucket["tests"].add(rel)
                else:
                    bucket["code"].add(rel)
    return index


def _status_for(code: Set[str], tests: Set[str]) -> str:
    if code and tests:
        return "covered"
    if code or tests:
        return "partial"
    return "gap"


def _code_cell(files: Set[str]) -> str:
    if not files:
        return "—"
    return "<br>".join("`{}`".format(f) for f in sorted(files))


def build_report() -> str:
    config = common.load_config()
    globs = common.traceability_globs(config)
    aliases = common.tag_aliases(config)
    name = common.project_name(config)

    declared: List[Requirement] = parse_requirements()
    declared_ids = {r.id for r in declared}
    index = scan(globs, aliases)

    rows: List[Tuple[str, str, Set[str], Set[str], str]] = []
    covered = 0
    gap_ids: List[str] = []
    for req in declared:
        bucket = index.get(req.id, {"code": set(), "tests": set()})
        code = bucket["code"]
        tests = bucket["tests"]
        status = _status_for(code, tests)
        if status == "covered":
            covered += 1
        if status == "gap":
            gap_ids.append(req.id)
        rows.append((req.id, req.source_doc, code, tests, status))

    # Tags that point at an id no document declares — an actionable error.
    unknown = sorted(
        rid for rid in index.keys() if rid not in declared_ids
    )

    total = len(declared)
    lines: List[str] = []
    lines.append(HEADER)
    lines.append("")
    lines.append("# {} — Traceability Matrix".format(name))
    lines.append("")
    lines.append(
        "> **GENERATED — DO NOT EDIT BY HAND.** Produced from `@requirement` / "
        "`@rule` tags in the source. Change the requirements and the tags, then "
        "regenerate via the sync skill."
    )
    lines.append("")
    lines.append(
        "**Coverage (declared requirements with code *and* test):** "
        "{}/{}".format(covered, total)
    )
    lines.append("")
    lines.append("> Status: `covered` (code + test) · `partial` (one side only) · `gap` (neither).")
    lines.append("")
    lines.append("## Matrix")
    lines.append("")
    lines.append("| Requirement ID | Source doc | Code | Tests | Status |")
    lines.append("| -------------- | ---------- | ---- | ----- | ------ |")
    if rows:
        for rid, src, code, tests, status in rows:
            lines.append(
                "| {} | `{}` | {} | {} | {} |".format(
                    rid, src, _code_cell(code), _code_cell(tests), status
                )
            )
    else:
        lines.append("| _none declared_ | | | | |")
    lines.append("")

    lines.append("## Gaps")
    lines.append("")
    lines.append(
        "- **Requirements with no coverage** ({}): {}".format(
            len(gap_ids), ", ".join(gap_ids) if gap_ids else "—"
        )
    )
    if unknown:
        lines.append(
            "- ⚠️ **Tags referencing an undeclared requirement** ({}): {} — "
            "fix the tag or declare the requirement in `docs/requirements/`.".format(
                len(unknown), ", ".join(unknown)
            )
        )
    lines.append("")

    return "\n".join(lines).rstrip("\n") + "\n"


def main(argv: List[str]) -> int:
    default_out = common.repo_path(
        common.generated_dir(), DEFAULT_OUT_BASENAME
    )
    check, out_path = common.parse_common_args(argv, default_out)
    content = build_report()
    return common.emit(content, out_path, check, "traceability")


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
